name: "Universal CI checks"
description: "A GitHub Action to run plethora of CI checks"
author: "grumpper"

inputs:
  # Python related feature setup
  python_checks:
    description: "Enable python checks as a whole"
    required: false
    default: true
  pylint_checks:
    description: "Enable python's pylint checks"
    required: false
    default: true
  bandit_checks:
    description: "Enable python's bandit checks"
    required: false
    default: true
  # Terraform related feature setup
  terraform_checks:
    description: "Enable terraform checks as a whole"
    required: false
    default: true
  terraform_fmt_checks:
    description: "Enable terraform's fmt checks"
    required: false
    default: true
  tflint_checks:
    description: "Enable terraform's TFLint checks"
    required: false
    default: true
  trivy_checks:
    description: "Enable terraform's Trivy checks"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    # Setup Taskfile
    - name: Set up Taskfile
      uses: arduino/setup-task@v2
      with:
        version: "3.x"
    # Run all CI checks via taskfile
    - name: Run CI checks
      shell: bash
      run: task $GITHUB_ACTION_PATH/taskfile.yml
      env:
        UCI_PYTHON_CHECKS: ${{ inputs.python_checks }}
        UCI_PYLINT_CHECKS: ${{ inputs.pylint_checks }}
        UCI_BANDIT_CHECKS: ${{ inputs.bandit_checks }}
        UCI_TERRAFORM_CHECKS: ${{ inputs.terraform_checks }}
        UCI_TERRAFORM_FMT_CHECKS: ${{ inputs.terraform_fmt_checks }}
        UCI_TFLINT_CHECKS: ${{ inputs.tflint_checks }}
        UCI_TRIVY_CHECKS: ${{ inputs.trivy_checks }}

branding:
  icon: "underline"
  color: "blue"
