name: "Universal CI checks"
description: "A GitHub Action to run plethora of CI checks"
author: "grumpper"

runs:
  using: "composite"
  steps:
    # Setup Taskfile
    - name: Set up Taskfile
      uses: arduino/setup-task@v2
      with:
        version: "3.x"

    # Setup UCI logger
    - name: Setup UCI logger
      shell: bash
      run: task -t $GITHUB_ACTION_PATH/taskfile.yml -d $GITHUB_WORKSPACE setup-logger

    # Run all CI checks via taskfile
    - name: Run CI checks
      shell: bash
      run: task -t $GITHUB_ACTION_PATH/taskfile.yml -d $GITHUB_WORKSPACE run-all-checks

    # Generate markdown summary
    - name: Generate Summary
      if: success() || failure()
      shell: bash
      run: task -t $GITHUB_ACTION_PATH/taskfile.yml -d $GITHUB_WORKSPACE generate-summary

branding:
  icon: "underline"
  color: "blue"
