version: '3'

silent: true
output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

includes:
  python:
    taskfile: ./tasks/python_checks.yml
    vars:
      UCI_PYLINT_CHECKS: $UCI_PYLINT_CHECKS
      UCI_BANDIT_CHECKS: $UCI_BANDIT_CHECKS
  terraform:
    taskfile: ./tasks/terraform_checks.yml
    vars:
      UCI_TERRAFORM_FMT_CHECKS: $UCI_TERRAFORM_FMT_CHECKS
      UCI_TFLINT_CHECKS: $UCI_TFLINT_CHECKS
      UCI_TRIVY_CHECKS: $UCI_TRIVY_CHECKS

tasks:
  python:default:
    preconditions:
      sh: '[[ "$UCI_PYTHON_CHECKS" == "true" ]]'
  terraform:default:
    preconditions:
      sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]]'
