version: '3'

silent: true

env:
  CLIENT_PATH: $GITHUB_WORKSPACE
  ACTION_PATH: $GITHUB_ACTION_PATH

dotenv: ['{{.CLIENT_PATH}}/.uci.env', '{{.ACTION_PATH}}/uci.env']

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

includes:
  python_tasks:
    taskfile: ./tasks/python_checks.yml
  terraform_tasks:
    taskfile: ./tasks/terraform_checks.yml

tasks:
  show_config:
    name: Show the configuration
    cmds:
      - env | grep -E 'PYTHON_|TERRAFORM_'
  python_checks:
    name: Run python checks
    deps:
      - python_tasks
    preconditions:
      - sh: '[[ "$PYTHON_CHECKS" == "true" ]]'
  terraform_checks:
    name: Run terraform checks
    deps:
      - terraform_tasks
    preconditions:
      - sh: '[[ "$TERRAFORM_CHECKS" == "true" ]]'
  default:
    deps:
      - show_config
#       - python_checks
#       - terraform_checks
