version: '3'

silent: true

env:
  CLIENT:
    sh: echo $GITHUB_WORKSPACE
  ACTION:
    sh: echo $GITHUB_ACTION_PATH

dotenv: ['{{.CLIENT}}/uci.env', '{{.ACTION}}/uci.env']

includes:
  python-tasks:
    taskfile: ./tasks/python.yml
  terraform-tasks:
    taskfile: ./tasks/terraform.yml
  summary-tasks:
    taskfile: ./tasks/summary.yml

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  setup-logger:
    name: Setup logger
    run: once
    cmds:
      - cp $GITHUB_ACTION_PATH/scripts/uci_looger.sh /usr/local/bin/uci_logger
      - chmod +x /usr/local/bin/uci_logger

  python-checks:
    name: Run python checks
    run: once
    cmds:
      - mkdir -p $GITHUB_WORKSPACE/reports/python
      - task: python-tasks:default
    status:
      - '[[ $UCI_PYTHON_CHECKS != "true" ]]'

  terraform-checks:
    name: Run terraform checks
    run: once
    cmds:
      - mkdir -p $GITHUB_WORKSPACE/reports/terraform
      - task: terraform-tasks:default
    status:
      - '[[ $UCI_TERRAFORM_CHECKS != "true" ]]'

  run-all-checks:
    name: Run all CI checks
    run: once
    deps:
      - python-checks
      - terraform-checks

  generate-summary:
    name: Generate checks Summary
    run: once
    cmds:
      - task: summary-tasks:default