version: '3'

silent: true

env:
  CLIENT:
    sh: echo $GITHUB_WORKSPACE
  ACTION:
    sh: echo $GITHUB_ACTION_PATH

dotenv: ['{{.CLIENT}}/uci.env', '{{.ACTION}}/uci.env']

includes:
  python_tasks:
    taskfile: ./tasks/python.yml
  terraform_tasks:
    taskfile: ./tasks/terraform.yml
  summary_tasks:
    taskfile: ./tasks/summary.yml

output:
  group:
    error_only: true
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  python_checks:
    name: Run python checks
    ignore_error: true
    run: once
    deps:
      - python_tasks:default
    status:
      - bash $GITHUB_ACTION_PATH/scripts/evaluate.sh $UCI_PYTHON_CHECKS

  terraform_checks:
    name: Run terraform checks
    ignore_error: true
    run: once
    deps:
      - terraform_tasks:default
    status:
      - bash $GITHUB_ACTION_PATH/scripts/evaluate.sh $UCI_TERRAFORM_CHECKS

  run_checks:
    ignore_error: true
    run: once
    deps:
      - python_checks
      - terraform_checks

  generate_summary:
    ignore_error: true
    run: once
    cmds:
      - echo "python" && bash $GITHUB_ACTION_PATH/scripts/evaluate.sh $UCI_PYTHON_CHECKS; echo $?; echo -e "\n"
      - echo "tf" && bash $GITHUB_ACTION_PATH/scripts/evaluate.sh $UCI_TERRAFORM_CHECKS; echo $?; echo -e "\n"
    deps:
      - run_checks

  default:
    ignore_error: true
    deps:
      - generate_summary