version: '3'

silent: true
output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  python_checks:
    name: Run Python Checks
    cmds:
      - task -t tasks/python_checks.yml
    preconditions:
      sh: '[[ "$UCI_PYTHON_CHECKS" == "true" ]]'
  terraform_checks:
    name: Run Terraform Checks
    cmds:
      - task -t tasks/terraform_checks.yml
    preconditions:
      sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]]'

  default:
    deps:
      - python_checks
      - terraform_checks
