version: '3'

silent: true

env:
  CLIENT:
    sh: echo $GITHUB_WORKSPACE
  ACTION:
    sh: echo $GITHUB_ACTION_PATH

dotenv: ['{{.CLIENT}}/uci.env', '{{.ACTION}}/uci.env']

includes:
  python_tasks:
    taskfile: ./tasks/python.yml
  terraform_tasks:
    taskfile: ./tasks/terraform.yml

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  # Print the related configuration
  main_config:
    label: MAIN CONFIG
    name: Prints technology related configuration
    cmds:
      - |
        echo "Python checks: $PYTHON_CHECKS"
        echo "Terraform checks: $TERRAFORM_CHECKS"
        if [[ "$TERRAFORM_CHECKS" == "true" ]]; then
          echo "true - do the checks"
        else
          echo "false - dont do the checks"
        fi

  python_checks:
    name: Run python checks
    deps:
      - main_config
      - python_tasks:default
    preconditions:
      - sh: '[[ "$PYTHON_CHECKS" == "true" ]]'

  terraform_checks:
    name: Run terraform checks
    deps:
      - main_config
      - terraform_tasks:default
    preconditions:
      - sh: '[[ "$TERRAFORM_CHECKS" == "true" ]]'

  default:
    deps:
      - main_config
      - python_checks
      - terraform_checks
