version: '3'

silent: true
output:
  group:
    # error_only: true
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  # Installations
  install_pylint:
    name: Install pylint
    internal: true
    cmds:
      - python3 -m pip install pylint
    preconditions:
      - sh: '[[ "$UCI_PYTHON_CHECKS" == "true" ]] && [[ "$UCI_PYLINT_CHECKS" == "true" ]]'
  install_bandit:
    name: Install bandit
    internal: true
    cmds:
      - python3 -m pip install bandit
    preconditions:
      - sh: '[[ "$UCI_PYTHON_CHECKS" == "true" ]] && [[ "$UCI_BANDIT_CHECKS" == "true" ]]'
  install_terraform:
    name: Install Terraform
    internal: true
    cmds:
      - bash $GITHUB_ACTION_PATH/scripts/install_terraform.sh
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]]'
  install_tflint:
    name: Install tflint
    internal: true
    cmds:
      - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - tflint --config "$(pwd)/.tflint.hcl" --init
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]]'
  install_trivy:
    name: Install trivy
    internal: true
    cmds:
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin ${UCI_TRIVY_VERSION}
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]]'
  # Python Checks
  run_pylint:
    name: Run pylint
    deps: [install_pylint]
    cmds:
      - pylint . --rcfile .pylintrc --recursive=y
    preconditions:
      - sh: '[[ "$UCI_PYTHON_CHECKS" == "true" ]] && [[ "$UCI_PYLINT_CHECKS" == "true" ]]'
  run_bandit:
    name: Run bandit
    deps: [install_bandit]
    cmds:
      - bandit -c .bandit.yml -r .
    preconditions:
      - sh: '[[ "$UCI_PYTHON_CHECKS" == "true" ]] && [[ "$UCI_BANDIT_CHECKS" == "true" ]]'
  # Terraform Checks
  run_terraform_fmt:
    name: Run terraform fmt
    deps: [install_terraform]
    cmds:
      - terraform fmt -recursive
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]] && [[ "$UCI_TERRAFORM_FMT_CHECKS" == "true" ]]'
  run_tflint:
    name: Run TFLint
    deps: [install_tflint]
    cmds:
      - tflint --config "$(pwd)/.tflint.hcl" --recursive
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]] && [[ "$UCI_TFLINT_CHECKS" == "true" ]]'
  run_trivy:
    name: Run Trivy
    deps: [install_trivy]
    cmds:
      - trivy config --config .trivy.yaml .
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]] && [[ "$UCI_TRIVY_CHECKS" == "true" ]]'

  default:
    deps:
      - run_pylint
      - run_bandit
      - run_terraform_fmt
      - run_tflint
      - run_trivy