version: '3'

silent: true

env:
  CLIENT:
    sh: echo $GITHUB_WORKSPACE
  ACTION:
    sh: echo $GITHUB_ACTION_PATH

dotenv: ['{{.CLIENT}}/uci.env', '{{.ACTION}}/uci.env']

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  python_checks:
    name: Run python checks
    cmds:
      - task -t {{.ACTION}}/tasks/python_checks.yml -v
    preconditions:
      - sh: '[[ "$PYTHON_CHECKS" == "true" ]]'
  terraform_checks:
    name: Run terraform checks
    cmds:
      - task -t {{.ACTION}}/tasks/terraform_checks.yml -v
    preconditions:
      - sh: '[[ "$TERRAFORM_CHECKS" == "true" ]]'
  default:
    deps:
      - python_checks
      - terraform_checks
