version: '3'

silent: true

env:
  CLIENT:
    sh: echo $GITHUB_WORKSPACE
  ACTION:
    sh: echo $GITHUB_ACTION_PATH

dotenv: ['{{.CLIENT}}/uci.env', '{{.ACTION}}/uci.env']

includes:
  python_tasks:
    taskfile: ./tasks/python.yml
  terraform_tasks:
    taskfile: ./tasks/terraform.yml

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  print_config:
    label: UCI CONFIG
    name: Prints the merged UCI configuration
    run: once
    cmds:
      - |
        echo "## Runtime Configuration" >> $GITHUB_STEP_SUMMARY
        echo "```shell" >> $GITHUB_STEP_SUMMARY
        bash $GITHUB_ACTION_PATH/scripts/print_configuration.sh >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY

  python_checks:
    name: Run python checks
    deps:
      - print_config
      - python_tasks:default
    status:
      - 'if [[ "$PYTHON_CHECKS" == "true" ]]; then exit 1; fi'

  terraform_checks:
    name: Run terraform checks
    deps:
      - print_config
      - terraform_tasks:default
    status:
      - 'if [[ "$TERRAFORM_CHECKS" == "true" ]]; then exit 1; fi'

  default:
    deps:
      - print_config
      - python_checks
      - terraform_checks
