version: '3'

silent: true
output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

includes:
  python:
    taskfile: ./tasks/python_checks.yml
    vars:
      UCI_PYLINT_CHECKS: $UCI_PYLINT_CHECKS
      UCI_BANDIT_CHECKS: $UCI_BANDIT_CHECKS
  terraform:
    taskfile: ./tasks/terraform_checks.yml
    vars:
      UCI_TERRAFORM_FMT_CHECKS: $UCI_TERRAFORM_FMT_CHECKS
      UCI_TFLINT_CHECKS: $UCI_TFLINT_CHECKS
      UCI_TRIVY_CHECKS: $UCI_TRIVY_CHECKS

tasks:

  default:
    desc: Default task that can be used to trigger the automation
    deps:
      - python
      - terraform
