version: '3'

silent: true

env:
  CLIENT:
    sh: echo $GITHUB_WORKSPACE
  ACTION:
    sh: echo $GITHUB_ACTION_PATH

dotenv: ['{{.CLIENT}}/uci.env', '{{.ACTION}}/uci.env']

includes:
  python_tasks:
    taskfile: ./tasks/python.yml
  terraform_tasks:
    taskfile: ./tasks/terraform.yml

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  print_env:
    name: Print environment variables
    run: once
    cmds:
      - env
  # Print the related configuration
  main_config:
    label: MAIN CONFIG
    name: Prints technology related configuration
    run: once
    cmds:
      - |
        echo "Python checks: $PYTHON_CHECKS"
        echo "Terraform checks: $TERRAFORM_CHECKS"

  python_checks:
    name: Run python checks
    deps:
      - main_config
      - python_tasks:default
    status:
      - 'if [[ "$PYTHON_CHECKS" == "true" ]]; then exit 1; fi'

  terraform_checks:
    name: Run terraform checks
    deps:
      - main_config
      - terraform_tasks:default
    status:
      - 'if [[ "$TERRAFORM_CHECKS" == "true" ]]; then exit 1; fi'

  default:
    deps:
      - print_env
      - main_config
      - python_checks
      - terraform_checks
