version: '3'

silent: true

env:
  CLIENT:
    sh: echo $GITHUB_WORKSPACE
  ACTION:
    sh: echo $GITHUB_ACTION_PATH

dotenv: ['{{.CLIENT}}/uci.env', '{{.ACTION}}/uci.env']

includes:
  python_tasks:
    taskfile: ./tasks/python.yml
  terraform_tasks:
    taskfile: ./tasks/terraform.yml

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  python_checks:
    name: Run python checks
    ignore_error: true
    deps:
      - python_tasks:default
    preconditions:
      - sh: '[[ "$PYTHON_CHECKS" == "true" ]]'
  terraform_checks:
    name: Run terraform checks
    ignore_error: true
    deps:
      - terraform_tasks:default
    preconditions:
      - sh: '[[ "$TERRAFORM_CHECKS" == "true" ]]'
  default:
    deps:
      - python_checks
      - terraform_checks
