version: '3'

silent: true
output:
  group:
    # error_only: true
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  # Installations
  install_python:
    label: Install Python & pip
    cmds:
      - bash $GITHUB_ACTION_PATH/scripts/install_python.sh
    preconditions:
      - sh: '[[ "$UCI_PYTHON_CHECKS" == "true" ]]'
  install_terraform:
    label: Install Terraform
    cmds:
      - bash $GITHUB_ACTION_PATH/scripts/install_terraform.sh
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]]'
  install_tflint:
    label: Install tflint
    cmds:
      - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]]'
  install_trivy:
    label: Install trivy
    cmds:
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin ${UCI_TRIVY_VERSION}
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]]'
  # Python Checks
  run_pylint:
    label: Run pylint
    deps: [install_python]
    cmds:
      - pylint . --rcfile .pylintrc --recursive=y
    preconditions:
      - sh: '[[ "$UCI_PYTHON_CHECKS" == "true" ]] && [[ "$UCI_PYLINT_CHECKS" == "true" ]]'
  run_bandit:
    label: Run bandit
    deps: [install_python]
    cmds:
      - bandit -c .bandit.yml -r .
    preconditions:
      - sh: '[[ "$UCI_PYTHON_CHECKS" == "true" ]] && [[ "$UCI_BANDIT_CHECKS" == "true" ]]'
  # Terraform Checks
  run_terraform_fmt:
    label: Run terraform fmt
    deps: [install_terraform]
    cmds:
      - terraform fmt -recursive
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]] && [[ "$UCI_TERRAFORM_FMT_CHECKS" == "true" ]]'
  run_tflint:
    label: Run TFLint
    deps: [install_tflint]
    cmds:
      - echo $PWD
      - ls -l
      - tflint -c .tflint.hcl --init
      - tflint -c .tflint.hcl --recursive
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]] && [[ "$UCI_TFLINT_CHECKS" == "true" ]]'
  run_trivy:
    label: Run Trivy
    deps: [install_trivy]
    cmds:
      - trivy config --config .trivy.yaml .
    preconditions:
      - sh: '[[ "$UCI_TERRAFORM_CHECKS" == "true" ]] && [[ "$UCI_TRIVY_CHECKS" == "true" ]]'

  default:
    deps:
      - run_pylint
      - run_bandit
      - run_terraform_fmt
      - run_tflint
      - run_trivy