version: '3'

silent: true

env:
  CLIENT:
    sh: echo $GITHUB_WORKSPACE
  ACTION:
    sh: echo $GITHUB_ACTION_PATH

dotenv: ['{{.CLIENT}}/uci.env', '{{.ACTION}}/uci.env']

includes:
  python_tasks:
    taskfile: ./tasks/python.yml
  terraform_tasks:
    taskfile: ./tasks/terraform.yml
  summary_tasks:
    taskfile: ./tasks/summary.yml

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  python_checks:
    name: Run python checks
    run: once
    cmds:
      - task: python_tasks:default
    status:
      - '[[ $UCI_PYTHON_CHECKS != "true" ]]'

  terraform_checks:
    name: Run terraform checks
    run: once
    cmds:
      - task: terraform_tasks:default
    status:
      - '[[ $UCI_TERRAFORM_CHECKS != "true" ]]'

  run_checks:
    name: Run all CI checks
    run: once
    deps:
      - python_checks
      - terraform_checks

  generate_summary:
    name: Generate checks Summary
    run: once
    cmds:
      - task: summary_tasks:default