version: '3'

silent: true

env:
  PYLINT_CONFIG:
    sh: |
      if [[ -f $GITHUB_WORKSPACE/.pylintrc ]]; then
        echo $GITHUB_WORKSPACE/.pylintrc
      else
        echo $GITHUB_ACTION_PATH/configs/.pylintrc
      fi
  BANDIT_CONFIG:
    sh: |
      if [[ -f $GITHUB_WORKSPACE/.bandit.yml ]]; then
        echo $GITHUB_WORKSPACE/.bandit.yml
      else
        echo $GITHUB_ACTION_PATH/configs/.bandit.yml
      fi

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  summary_header:
    name: Execute python checks
    run: once
    cmds:
      - printf '## Python\n' >> $GITHUB_STEP_SUMMARY
  # Installations
  upgrade_pip:
    name: Upgrade pip
    deps: [summary_header]
    run: once
    internal: true
    cmds:
      - python3 -m pip install --user --upgrade pip
  install_pylint:
    name: Install pylint
    run: once
    deps: [upgrade_pip]
    internal: true
    cmds:
      - pip install --user --upgrade pylint
    status:
      - 'if [[ "$PYTHON_PYLINT_CHECKS" == "true" ]]; then exit 1; fi'
  install_bandit:
    name: Install bandit
    run: once
    deps: [upgrade_pip]
    internal: true
    cmds:
      - pip install --user --upgrade bandit
    status:
      - 'if [[ "$PYTHON_BANDIT_CHECKS" == "true" ]]; then exit 1; fi'

  # Checks
  run_pylint:
    name: Run pylint
    deps: [install_pylint]
    cmds:
      - |
        printf '### Pylint\n' >> $GITHUB_STEP_SUMMARY
        printf '```shell \n' >> $GITHUB_STEP_SUMMARY
        pylint --rcfile {{.PYLINT_CONFIG}} --recursive=y $GITHUB_WORKSPACE | tee -a $GITHUB_STEP_SUMMARY
        printf '```\n' >> $GITHUB_STEP_SUMMARY
    status:
      - 'if [[ "$PYTHON_PYLINT_CHECKS" == "true" ]]; then exit 1; fi'
  run_bandit:
    name: Run bandit
    deps: [install_bandit]
    cmds:
      - |
        printf '### Bandit\n' >> $GITHUB_STEP_SUMMARY
        printf '```shell \n' >> $GITHUB_STEP_SUMMARY
        bandit -c {{.BANDIT_CONFIG}} -r $GITHUB_WORKSPACE | tee -a $GITHUB_STEP_SUMMARY
        printf '```\n' >> $GITHUB_STEP_SUMMARY
    status:
      - 'if [[ "$PYTHON_BANDIT_CHECKS" == "true" ]]; then exit 1; fi'

  default:
    deps:
      - run_pylint
      - run_bandit
