version: '3'

silent: true
output:
  group:
    # error_only: true
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  # Installations
  check_env:
    name: Check environment
    internal: true
    cmds:
      - env
  setup_venv:
    name: Setup virtual environment
    internal: true
    cmds:
      - python3 -m venv venv
      - source venv/bin/activate
  install_pylint:
    name: Install pylint
    deps: [setup_venv]
    internal: true
    cmds:
      - pip install pylint
    preconditions:
      - sh: '[[ "$UCI_PYLINT_CHECKS" == "true" ]]'
  install_bandit:
    name: Install bandit
    deps: [setup_venv]
    internal: true
    cmds:
      - pip install bandit
    preconditions:
      - sh: '[[ "$UCI_BANDIT_CHECKS" == "true" ]]'

  # Checks
  run_pylint:
    name: Run pylint
    deps: [install_pylint]
    cmds:
      - pylint . --rcfile .pylintrc --recursive=y
    preconditions:
      - sh: '[[ "$UCI_PYLINT_CHECKS" == "true" ]]'
  run_bandit:
    name: Run bandit
    deps: [install_bandit]
    cmds:
      - bandit -c .bandit.yml -r .
    preconditions:
      - sh: '[[ "$UCI_BANDIT_CHECKS" == "true" ]]'

  default:
    deps:
      - run_pylint
      - run_bandit
