version: '3'

silent: true

env:
  PYLINT_CONFIG:
    sh: |
      if [[ -f $GITHUB_WORKSPACE/.pylintrc ]]; then
        echo $GITHUB_WORKSPACE/.pylintrc
      else
        echo $GITHUB_ACTION_PATH/configs/.pylintrc
      fi
  BANDIT_CONFIG:
    sh: |
      if [[ -f $GITHUB_WORKSPACE/.bandit.yml ]]; then
        echo $GITHUB_WORKSPACE/.bandit.yml
      else
        echo $GITHUB_ACTION_PATH/configs/.bandit.yml
      fi

output:
  group:
    # error_only: true
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  # Installations
  upgrade_pip:
    name: Upgrade pip
    internal: true
    cmds:
      - python3 -m pip install --user --upgrade pip
  install_pylint:
    name: Install pylint
    deps: [upgrade_pip]
    internal: true
    cmds:
      - pip install --user --upgrade pylint
    preconditions:
      - sh: '[[ "$PYTHON_PYLINT_CHECKS" == "true" ]]'
  install_bandit:
    name: Install bandit
    deps: [upgrade_pip]
    internal: true
    cmds:
      - pip install --user --upgrade bandit
    preconditions:
      - sh: '[[ "$PYTHON_BANDIT_CHECKS" == "true" ]]'

  # Checks
  run_pylint:
    name: Run pylint
    deps: [install_pylint]
    cmds:
      - pylint . --rcfile {{.PYLINT_CONFIG}} --recursive=y
    preconditions:
      - sh: '[[ "$PYTHON_PYLINT_CHECKS" == "true" ]]'
  run_bandit:
    name: Run bandit
    deps: [install_bandit]
    cmds:
      - bandit -c {{.BANDIT_CONFIG}} -r .
    preconditions:
      - sh: '[[ "$PYTHON_BANDIT_CHECKS" == "true" ]]'

  default:
    deps:
      - run_pylint
      - run_bandit
