version: '3'

silent: true

env:
  PYLINT_CONFIG:
    sh: |
      if [[ -f $GITHUB_WORKSPACE/.pylintrc ]]; then
        echo $GITHUB_WORKSPACE/.pylintrc
      else
        echo $GITHUB_ACTION_PATH/configs/.pylintrc
      fi
  BANDIT_CONFIG:
    sh: |
      if [[ -f $GITHUB_WORKSPACE/.bandit.yml ]]; then
        echo $GITHUB_WORKSPACE/.bandit.yml
      else
        echo $GITHUB_ACTION_PATH/configs/.bandit.yml
      fi

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  # Installations
  upgrade_pip:
    name: Upgrade pip
    run: once
    internal: true
    cmds:
      - python3 -m pip install --user --upgrade pip
  install_pylint:
    name: Install pylint
    run: once
    deps: [upgrade_pip]
    internal: true
    cmds:
      - pip install --user --upgrade pylint
    status:
      - bash $GITHUB_ACTION_PATH/scripts/evaluate.sh $UCI_PYTHON_PYLINT_CHECKS
  install_bandit:
    name: Install bandit
    run: once
    deps: [upgrade_pip]
    internal: true
    cmds:
      - pip install --user --upgrade bandit
    status:
      - bash $GITHUB_ACTION_PATH/scripts/evaluate.sh $UCI_PYTHON_BANDIT_CHECKS

  # Checks
  run_pylint:
    name: Run pylint
    run: once
    deps: [install_pylint]
    cmds:
      - pylint --rcfile {{.PYLINT_CONFIG}} --recursive=y $GITHUB_WORKSPACE
    status:
      - bash $GITHUB_ACTION_PATH/scripts/evaluate.sh $UCI_PYTHON_PYLINT_CHECKS
  run_bandit:
    name: Run bandit
    run: once
    deps: [install_bandit]
    cmds:
      - bandit -c {{.BANDIT_CONFIG}} -r $GITHUB_WORKSPACE
    status:
      - bash $GITHUB_ACTION_PATH/scripts/evaluate.sh $UCI_PYTHON_BANDIT_CHECKS

  default:
    run: once
    deps:
      - run_pylint
      - run_bandit
