version: '3'

silent: true
output:
  group:
    # error_only: true
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  # Installations
  check_env:
    name: Check environment
    internal: true
    cmds:
      - env
  upgrade_pip:
    name: Upgrade pip
    internal: true
    cmds:
      - python -m pip install --upgrade pip
  install_pylint:
    name: Install pylint
    deps: [upgrade_pip]
    internal: true
    cmds:
      - pip install --user --upgrade pylint
    preconditions:
      - sh: '[[ "$UCI_PYLINT_CHECKS" == "true" ]]'
    status:
      - pylint --version
  install_bandit:
    name: Install bandit
    deps: [upgrade_pip]
    internal: true
    cmds:
      - pip install --user --upgrade bandit
    preconditions:
      - sh: '[[ "$UCI_BANDIT_CHECKS" == "true" ]]'
    status:
      - bandit --version

  # Checks
  run_pylint:
    name: Run pylint
    deps: [install_pylint]
    cmds:
      - pylint . --rcfile .pylintrc --recursive=y
    preconditions:
      - sh: '[[ "$UCI_PYLINT_CHECKS" == "true" ]]'
  run_bandit:
    name: Run bandit
    deps: [install_bandit]
    cmds:
      - bandit -c .bandit.yml -r .
    preconditions:
      - sh: '[[ "$UCI_BANDIT_CHECKS" == "true" ]]'

  default:
    deps:
      - run_pylint
      - run_bandit
