version: '3'

silent: true

env:
  TFLINT_CONFIG:
    sh: |
      if [[ -f $GITHUB_WORKSPACE/.tflint.hcl ]]; then
        echo $GITHUB_WORKSPACE/.tflint.hcl
      else
        echo $GITHUB_ACTION_PATH/configs/.tflint.hcl
      fi
  TRIVY_CONFIG:
    sh: |
      if [[ -f $GITHUB_WORKSPACE/.trivy.yml ]]; then
        echo $GITHUB_WORKSPACE/.trivy.yml
      else
        echo $GITHUB_ACTION_PATH/configs/.trivy.yml
      fi

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  summary_header:
    name: Execute terraform checks
    run: once
    cmds:
      - printf '## Terraform\n' >> $GITHUB_STEP_SUMMARY
  # Installations
  install_terraform:
    name: Install Terraform
    deps: [summary_header]
    run: once
    internal: true
    cmds:
      - bash $GITHUB_ACTION_PATH/scripts/install_terraform.sh
    status:
      - 'if [[ "$TERRAFORM_FMT_CHECKS" == "true" ]]; then exit 1; fi'
  install_tflint:
    name: Install TFLint
    deps: [summary_header]
    run: once
    internal: true
    cmds:
      - |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        tflint --config {{.TFLINT_CONFIG}} --init
    status:
      - 'if [[ "$TERRAFORM_TFLINT_CHECKS" == "true" ]]; then exit 1; fi'
  install_trivy:
    name: Install trivy
    deps: [summary_header]
    run: once
    internal: true
    cmds:
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.55.1
    status:
      - 'if [[ "$TERRAFORM_TRIVY_CHECKS" == "true" ]]; then exit 1; fi'

  # Checks
  run_terraform_fmt:
    name: Run terraform fmt
    deps: [install_terraform]
    cmds:
      - |
        printf '### Terraform fmt\n' >> $GITHUB_STEP_SUMMARY
        printf '```shell \n' >> $GITHUB_STEP_SUMMARY
        terraform fmt -recursive $GITHUB_WORKSPACE | tee -a $GITHUB_STEP_SUMMARY
        printf '```\n' >> $GITHUB_STEP_SUMMARY
    status:
      - 'if [[ "$TERRAFORM_FMT_CHECKS" == "true" ]]; then exit 1; fi'
  run_tflint:
    name: Run TFLint
    deps: [install_tflint]
    cmds:
      - |
        printf '### TFLint\n' >> $GITHUB_STEP_SUMMARY
        printf '```shell \n' >> $GITHUB_STEP_SUMMARY
        tflint --config {{.TFLINT_CONFIG}} --recursive $GITHUB_WORKSPACE | tee -a $GITHUB_STEP_SUMMARY
        printf '```\n' >> $GITHUB_STEP_SUMMARY
    status:
      - 'if [[ "$TERRAFORM_TFLINT_CHECKS" == "true" ]]; then exit 1; fi'
  run_trivy:
    name: Run Trivy
    deps: [install_trivy]
    cmds:
      - |
        printf '### Trivy\n' >> $GITHUB_STEP_SUMMARY
        printf '```shell \n' >> $GITHUB_STEP_SUMMARY
        trivy config -c {{.TRIVY_CONFIG}} $GITHUB_WORKSPACE/ | tee -a $GITHUB_STEP_SUMMARY
        printf '```\n' >> $GITHUB_STEP_SUMMARY
    status:
      - 'if [[ "$TERRAFORM_TRIVY_CHECKS" == "true" ]]; then exit 1; fi'

  default:
    deps:
      - run_terraform_fmt
      - run_tflint
      - run_trivy
