version: '3'

silent: true

env:
  CLIENT_PATH: $GITHUB_WORKSPACE
  ACTION_PATH: $GITHUB_ACTION_PATH

output:
  group:
    # error_only: true
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  # Installations
  check_env:
    name: Check environment
    internal: true
    cmds:
      - env
  install_terraform:
    name: Install Terraform
    internal: true
    cmds:
      - bash {{.ACTION_PATH}}/scripts/install_terraform.sh
    preconditions:
      - sh: '[[ "$TERRAFORM_FMT_CHECKS" == "true" ]]'
  install_tflint:
    name: Install tflint
    internal: true
    cmds:
      - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - tflint --config {{.CLIENT_PATH}}/.tflint.hcl --init
    preconditions:
      - sh: '[[ "$TERRAFORM_TFLINT_CHECKS" == "true" ]]'
  install_trivy:
    name: Install trivy
    internal: true
    cmds:
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.55.1
    preconditions:
      - sh: '[[ "$TERRAFORM_TRIVY_CHECKS" == "true" ]]'

  # Checks
  run_terraform_fmt:
    name: Run terraform fmt
    deps: [install_terraform]
    cmds:
      - terraform fmt -recursive {{.CLIENT_PATH}}
    preconditions:
      - sh: '[[ "$TERRAFORM_FMT_CHECKS" == "true" ]]'
  run_tflint:
    name: Run TFLint
    deps: [install_tflint]
    cmds:
      - tflint --config {{.CLIENT_PATH}}/.tflint.hcl --recursive
    preconditions:
      - sh: '[[ "$TERRAFORM_TFLINT_CHECKS" == "true" ]]'
  run_trivy:
    name: Run Trivy
    deps: [install_trivy]
    cmds:
      - trivy config --config {{.CLIENT_PATH}}/.trivy.yaml .
    preconditions:
      - sh: '[[ "$TERRAFORM_TRIVY_CHECKS" == "true" ]]'

  default:
    deps:
      - run_terraform_fmt
      - run_tflint
      - run_trivy
