version: '3'

silent: true

env:
  TFLINT_CONFIG:
    sh: |
      if [[ -f $GITHUB_WORKSPACE/.tflint.hcl ]]; then
        echo $GITHUB_WORKSPACE/.tflint.hcl
      else
        echo $GITHUB_ACTION_PATH/configs/.tflint.hcl
      fi
  TRIVY_CONFIG:
    sh: |
      if [[ -f $GITHUB_WORKSPACE/.trivy.yml ]]; then
        echo $GITHUB_WORKSPACE/.trivy.yml
      else
        echo $GITHUB_ACTION_PATH/configs/.trivy.yml
      fi

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  # Installations
  install_terraform:
    name: Install Terraform
    internal: true
    cmds:
      - bash $GITHUB_ACTION_PATH/scripts/install_terraform.sh
    preconditions:
      - sh: '[[ "$TERRAFORM_FMT_CHECKS" == "true" ]]'
  install_tflint:
    name: Install TFLint
    internal: true
    cmds:
      - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - tflint --config {{.TFLINT_CONFIG}} --init
    preconditions:
      - sh: '[[ "$TERRAFORM_TFLINT_CHECKS" == "true" ]]'
  install_trivy:
    name: Install trivy
    internal: true
    cmds:
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.55.1
    preconditions:
      - sh: '[[ "$TERRAFORM_TRIVY_CHECKS" == "true" ]]'

  # Checks
  run_terraform_fmt:
    name: Run terraform fmt
    deps: [install_terraform]
    cmds:
      - terraform fmt -recursive $GITHUB_WORKSPACE
    preconditions:
      - sh: '[[ "$TERRAFORM_FMT_CHECKS" == "true" ]]'
  run_tflint:
    name: Run TFLint
    deps: [install_tflint]
    cmds:
      - tflint --config {{.TFLINT_CONFIG}} --recursive
    preconditions:
      - sh: '[[ "$TERRAFORM_TFLINT_CHECKS" == "true" ]]'
  run_trivy:
    name: Run Trivy
    deps: [install_trivy]
    cmds:
      - trivy config -c {{.TRIVY_CONFIG}} -f sarif $GITHUB_WORKSPACE/
    preconditions:
      - sh: '[[ "$TERRAFORM_TRIVY_CHECKS" == "true" ]]'

  default:
    deps:
      - run_terraform_fmt
      - run_tflint
      - run_trivy
