name: Tag and Release

on:
  push:
    branches:
      - "main"

jobs:
  create-tag:
    name: Create New Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create New Tag
        id: create
        run: |
          TAG=$(cat VERSION)
          MSG=$(git --no-pager log -1 --format=%B)
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git tag -a ${TAG} -m "${MSG}"
          git push origin $TAG
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.create.outputs.tag }}

  update-tag:
    name: Update Major Version Tag
    needs: [ create-tag ]
    runs-on: ubuntu-latest
    steps:
      - name: Update Major Version Tag
        uses: nowactions/update-majorver@v1

  create-release:
    name: Create New Release
    needs: [ update-tag ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create New Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: ${{jobs.create-tag.outputs.tag}}
          generate_release_notes: true
