name: Tag during Development

on:
  push:
    pull_request:
      branches-ignore:
        - main

jobs:
  create-tag:
    name: Create New Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create New Tag
        id: create
        run: |
          TAG=$(git --no-pager branch --show-current)
          MSG=$(git --no-pager log -1 --format=%B)
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git tag -f -a ${TAG} -m "${MSG}"
          git push origin $TAG -f
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.create.outputs.tag }}
