name: Tag and Release

on:
  push:
    branches:
      - "main"

jobs:
  create-tag:
    name: Create New Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create New Tag
        id: create
        run: |
          TAG=$(cat VERSION)
          MAJOR_VERSION=$(echo $TAG | cut -d. -f1)
          MSG=$(git --no-pager log -1 --format=%B)
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git tag -a ${TAG} -m "${MSG}"
          git push origin $TAG
          git tag -f -a ${MAJOR_VERSION} -m "${MSG}"
          git push origin $MAJOR_VERSION -f
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.create.outputs.tag }}

  create-release:
    name: Create New Release
    needs: [ create-tag ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Generate Pet Name
        run: |
          pip install petname
          echo "PETNAME=$(petname -l 20 -s " "| sed 's/\b\(.\)/\u\1/g')" >> "$GITHUB_ENV"
      - name: Create New Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          name: "${{needs.create-tag.outputs.tag}} ${{env.PETNAME}}"
          tag_name: ${{needs.create-tag.outputs.tag}}
          generate_release_notes: true
          make_latest: true
